# Generated by Django 6.0.5 on 2026-09-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('LOOKING_FOR_CONTRIBUTORS', 'Looking for Contributors'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], max_length=50),
        ),
    ]
